server:
  port: 8001
  context-path: /forum
mybatis-plus:
  global-config:
    refresh: true
  mapper-locations: classpath:mapper/*
  type-enums-package: com.ylzinfo.forum.enums
spring:
  datasource:
    url: jdbc:mysql://192.168.43.33:3306/info-platform?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: ylzinfo
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
logging:
  level:
    com.ylzinfo.forum.mapper: debug