server:
  port: 8005
mybatis-plus:
  global-config:
    refresh: true
spring:
  datasource:
    url: jdbc:mysql://192.168.56.130:3306/info-platform?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
logging:
  level:
    com.ylzinfo.forum.mapper: debug